<script>
	var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() 
    {
    if (this.readyState == 4 && this.status == 200) {
     //document.getElementById("demo").innerHTML = this.responseText;
     console.log(JSON.parse(this.responseText));
     var obj = JSON.parse(this.responseText);
      Object.keys(obj).forEach(function(key){
      	console.log(key);
        console.log(obj[key]);
       });
    }
   };
  xhttp.open("GET", "<?php echo base_url();?>Api/ajaxcall", true);
  xhttp.send();
</script>

<?php
/*
$postdata = [
    'descriptions' => 'This content generated by curl UPDATED BY CURL ',
    'created_by' => 'curl method',
    'category_id'   => '2',
];
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_PORT            => "8000",
  CURLOPT_URL             => "http://localhost:8000/api/rest/users/2",
  CURLOPT_RETURNTRANSFER  => true,
  CURLOPT_ENCODING        => "",
  CURLOPT_MAXREDIRS       => 10,
  CURLOPT_TIMEOUT         => 30,
  CURLOPT_HTTP_VERSION    => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST   => "PUT",
  CURLOPT_POSTFIELDS      => $postdata,
  CURLOPT_HTTPHEADER      => array(
    "Postman-Token: 86f00973-a642-46e2-86ad-a60c5652ef3f",
    "cache-control: no-cache"
  ),
));
$response = curl_exec($curl);
$err = curl_error($curl);
curl_close($curl);
if ($err) 
{
  echo "cURL Error #:" . $err;
} else 
{
  echo $response;
}*/
?>